baseURL = "https://mhagnumdw.github.io"
languageCode = 'en-us'
title = 'MhagnumDw'
theme = 'FeelIt'
canonifyURLs = true # quebra a busca (search)
enableEmoji = true

# whether to use git commit log
enableGitInfo = true

[params]
  # FeelIt theme version
  version = "1.0.X"
  # site description
  description = "Programação, configuração, script, Linux e afins"
  # site keywords
  keywords = ["Blog", "Tech"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/mhagnumdw/mhagnumdw.github.io"
  # which hash function used for SRI, when empty, no SRI is used
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # date format
  dateFormat = "02/01/2006"
  # website images for Open Graph and Twitter Cards
  images = ["/img/caduceus.jpg"]
  # whether to enable CSS and JS source mapping
  SourceMap = true

  [params.header.title]
    # URL of the LOGO
    logo = "/img/caduceus.jpg"
    # title name
    name = "MhagnumDw"
    # whether to use typeit animation for title name
    typeit = false
    # whether to show RSS icon
    rss = true

  # Search config
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "Use asterisco para busca parcial, ex: test*"
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Page config
  [params.page]
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show link to improve the article
    improveArticle = "https://github.com/mhagnumdw/mhagnumdw.github.io/edit/master/content/"

  [params.page.code]
    maxShownLines = -1

  # Responsável por /posts
  [params.section]
    # special amount of posts in each section page
    paginate = 100
    # date format (month and day)
    dateFormat = "02/01/2006"

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 20
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/img/cropped-codecode.jpg"
      # title shown in home page (HTML format is supported)
      title = "Programação, configuração, script, Linux e afins"
      # subtitle shown in home page
      subtitle = ""
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 20
      # display image-preview
      imagePreview = true

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fa-brands fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/mhagnumdw"
    title = "GitHub"
    weight = 4
  # Comment config
  [params.page.comment]
    enable = true
    # Disqus comment config (https://disqus.com/)
    [params.page.comment.disqus]
      enable = true
      # Disqus shortname to use Disqus in posts
      shortname = "mhagnumdw"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false

    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    lineAnchors = ''
    lineNos = true
    style = 'monokai'

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
